### PR TITLE
Add myself

### PR DESCRIPTION
**Pull request by benjamingr**

### CODE REVIEW

**Review by abrl91 — CHANGES_REQUESTED** [review]
Hi Benjamin :)
For consistency, please change your name and description to Hebrew

p.s
It's really weird to approve your PR.
I think I will add it to my resume

**Comment by benjamingr** [comment]
In general it is good mannered to allow people to write their name and description (and pronouns!) however they choose.

As an example: here is Refack (who used to be in Israel and is Israeli) using הוא/אתה and his Hebrew name in Node https://github.com/nodejs/node/pull/27940 :]

**Comment by benjamingr** [comment]
That said, if you feel strongly - feel free to rename: בנימין גרינבאום. 

The pun doesn't really translate to Hebrew though :D

**Comment by abrl91** [comment]
@urish 
Should we let people write their name and description however they want?

**Review by abrl91 — APPROVED** [review]

**Pull request merged**
