### PR TITLE
Create yonatan-kra.json

### PR DESCRIPTION
**Pull request by YonatanKra**

### CODE REVIEW

**Comment by YonatanKra** [comment]
@urish dunno why it failed.

**Comment by urish** [comment]
Not your bad - it's something with the permissions of the script that validates the JSON

**Comment by abrl91** [comment]
@YonatanKra 
Hi Yonatan, can you please write the description and your name in Hebrew.
It seems like you have changed it but in the last commit the description is written in English and also there are missing properties (like your name).

**Comment by MichalPorag** [comment]
Hi Yonatan, can you please change the

**Comment by MichalPorag** [comment]
@YonatanKra 
Hi, can you please solve the problems?

**Comment by YonatanKra** [comment]
@MichalPorag I tried. Have no idea what I'm doing wrong.

**Pull request merged**
