### PR TITLE
Added filter capabilities

### PR DESCRIPTION
**Pull request by asharonbaltazar**
(Due to @MichalPorag's instructions, I left out the search functionality). Also due to inactivity, I deleted this repo last week and had to recreate the components from scratch 😬, but I didn't want to lose this chance for a PR.  Lesson learned. 

This PR adds a dynamic dropdown component that sifts through people. To avoid adding too many conditionals in the `people.map`, I took an abstract route and decided an array with all the filters is the way to go. This way, any future contributor can simply add a similar set of data and all filtering capabilities for that new dataset will be automatically enabled, as well as a new dropdown component representing that data (with all included functionality).

### CODE REVIEW

**Comment by binarica** [comment]
@asharonbaltazar could you squash the commits into one?

**Comment by asharonbaltazar** [comment]
כן, אין בעיה, אבל מאוחר יותר.

**Comment by ozizhakGT** [comment]
hi @asharonbaltazar 
please add responsive design
tnx alot!

**Comment by asharonbaltazar** [comment]
Hey, @ozizhakGT. Thanks for the response. 

Unfortunately, due to an exchange that happened off of GitHub with one of your core members and left me feeling rather unappreciated, I no longer want to participate in this PR wholeheartedly. Whatever work I've done until this point is yours to build on, but this is as far as I'll go.

Terribly sorry.

**Pull request closed without merging**
