### PR TITLE
Create a community member ronfybish.json file

### PR DESCRIPTION
**Pull request by ronfybish**
Good luck my dear friends (:
Great project I really liked the idea 💯

### CODE REVIEW

**Review by abrl91 — CHANGES_REQUESTED** [review]
Hi Ron, please change your name and description to Hebrew for consistency

**Comment by ronfybish** [comment]
@abrl91 Sure! 
You can also open issue on it related to the README doc.

"For consistency, when you create new member file pay attention that name and description fields should be in Hebrew"

**Comment by abrl91** [comment]
There is a line in the README file which says:
The name, github, and description fields are required and need to be in Hebrew.
All the other fields are optional

**Comment by ronfybish** [comment]
@abrl91 Wow right sorry it's my mistake I did not notice it 🤦

thanks Amit 🙏

**Review by ronfybish — COMMENTED** [review]
@abrl91  Amit following your request (💯

**Review by abrl91 — APPROVED** [review]

**Pull request merged**
